name: Génération du CV

on:
  push:
    branches:
      - main

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate PDF & HTML
        run: |
          npx resume export docs/resume.pdf --theme macchiato
          npx resume export docs/index.html --format html --theme macchiato

      - name: List generated files
        run: ls -la docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true
