name: Génération du CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer JSON Resume CLI
        run: npm install -g resume-cli

      - name: Générer PDF & HTML
        run: |
          mkdir -p docs
          resume export docs/resume.pdf --theme macchiato
          resume export docs/index.html --format html --theme macchiato

      - name: Commit & push sur gh-pages
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          git add docs/
          git commit -m "📄 Mise à jour automatique du CV"
          git push -f origin gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs